imports:
    - { resource: tables.yml }
services:
    dmzx.downloadlimit.admin.controller:
        class: dmzx\downloadlimit\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@request'
            - '@dbal.conn'
    dmzx.downloadlimit.cron.task.core.downloadlimit:
        class: dmzx\downloadlimit\cron\downloadlimit_prune
        arguments:
            - '@user'
            - '@config'
            - '@dbal.conn'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.downloadlimit.table.downloadlimit%'
        calls:
            - [set_name, [cron.task.core.downloadlimit]]
        tags:
            - { name: cron.task }
    dmzx.downloadlimit.listener:
        class: dmzx\downloadlimit\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.downloadlimit.table.downloadlimit%'
        tags:
            - { name: event.listener }